server:
  port: 9080

spring:
  application:
    name: eureka-server

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: "http://127.0.0.1:9080/eureka/"

  server:
    enable-self-preservation: false